class Codes:

	codes = {
		'0x0' : 'STATUS',
		'0x1' : 'FREEZE_DTC',
		'0x2' : 'FUEL_STATUS',
		'0x3' : 'ENGINE_LOAD',
		'0x4' : 'STATUS',
		'0x5' : 'FREEZE_DTC',
		'0x6' : 'FUEL_STATUS',
		'0x7' : 'ENGINE_LOAD',
		'0x8' : 'STATUS',
		'0x9' : 'FREEZE_DTC',
		'0xa' : 'FUEL_STATUS',
		'0xb' : 'ENGINE_LOAD',
		'0xc' : 'STATUS',
		'0xd' : 'FREEZE_DTC',
		'0xe' : 'FUEL_STATUS',
		'0xf' : 'ENGINE_LOAD',
		'0x10' : 'STATUS',
		'0x11' : 'FREEZE_DTC',
		'0x12' : 'FUEL_STATUS',
		'0x13' : 'ENGINE_LOAD',
		'0x14' : 'STATUS',
		'0x15' : 'FREEZE_DTC',
		'0x16' : 'FUEL_STATUS',
		'0x17' : 'ENGINE_LOAD',
		'0x18' : 'STATUS',
		'0x19' : 'FREEZE_DTC',
		'0x1a' : 'FUEL_STATUS',
		'0x1b' : 'ENGINE_LOAD',
		'0x1c' : 'STATUS',
		'0x1d' : 'FREEZE_DTC',
		'0x1e' : 'FUEL_STATUS',
		'0x1f' : 'ENGINE_LOAD',
	}